### ISSUE TITLE
Error no matter what argument i run picoblog-py with

### ISSUE THREAD

**Issue by sorenpeter** [hxii/picoblog-py#1]
I get this error when trying to run your new picoblog-py:
```
~/Desktop/git-repos/picoblog-py $ python main.py twtxt.txt index.html
  File "main.py", line 12
    def _load_twtxt_from_file(txt_path: str) -> dict:
                                      ^
SyntaxError: invalid syntax
```
Am I missing something?

**Comment by hxii** [comment]
Should've probably written it in the readme, but I ran this with Python 3.8+.
Which version are you trying to run it with?

**Comment by sorenpeter** [comment]
I was running it with the outdated pyton2 on MacOS.
Using python3.10 did the trick. thank you:)
